version: "3.9"

volumes:
  database:

services:
  db:
    image: postgres:12
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=urlshortcut_db
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  app:
    image: shortcut
    container_name: shortcut
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/urlshortcut_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 80:8080
    depends_on:
      - db